const DEMOS = {
    barbearia: { name:"Japa na Barba", segment:"Barbearia", icon:"✂", color:"#e9c765", pitch:"Agenda, clientes e desempenho da barbearia em um só lugar.", clients:284, appointments:96, revenue:12840, occupancy:82, services:[["Corte masculino",45,86],["Corte + barba",75,62],["Barba",35,48],["Platinado",120,21]], team:["Carlos Mendes","Rafael Lima","Bruno Alves"], sample:[["09:00","André Souza","Corte masculino","Carlos"],["10:30","Lucas Martins","Corte + barba","Rafael"],["13:00","Pedro Rocha","Barba","Bruno"]], insight:"Corte + barba cresceu 18% e já representa o melhor ticket médio da semana." },
    salao: { name:"Studio Bella Forma", segment:"Salão de beleza", icon:"✦", color:"#d67ae4", pitch:"Uma gestão elegante para agenda, equipe e recorrência das clientes.", clients:418, appointments:143, revenue:21950, occupancy:76, services:[["Corte feminino",120,54],["Escova",70,83],["Coloração",240,31],["Hidratação",95,47]], team:["Camila Rocha","Fernanda Luz","Aline Costa"], sample:[["09:00","Mariana Alves","Coloração","Camila"],["10:30","Paula Nunes","Escova","Fernanda"],["14:00","Renata Melo","Corte feminino","Aline"]], insight:"Clientes que combinam coloração e hidratação retornam, em média, 12 dias mais cedo." },
    manicure: { name:"Nail Art Boutique", segment:"Manicure e esmalteria", icon:"◇", color:"#ef8eb6", pitch:"Horários organizados, catálogo de serviços e fidelização sem esforço.", clients:326, appointments:168, revenue:11420, occupancy:88, services:[["Mão e pé",65,102],["Alongamento em gel",160,44],["Manutenção de gel",95,61],["Spa dos pés",75,38]], team:["Bianca Souza","Lívia Ramos","Nayara Dias"], sample:[["08:30","Ana Clara","Manutenção de gel","Bianca"],["10:00","Juliana Reis","Mão e pé","Lívia"],["13:30","Cláudia Lima","Alongamento em gel","Nayara"]], insight:"A manutenção automática por lembrete reduziu em 23% os horários ociosos." },
    estetica: { name:"Lumina Estética", segment:"Clínica de estética", icon:"◉", color:"#78d7c5", pitch:"Protocolos, sessões e evolução de cada cliente com visão profissional.", clients:231, appointments:87, revenue:28400, occupancy:73, services:[["Limpeza de pele",150,42],["Drenagem linfática",130,57],["Microagulhamento",320,18],["Massagem modeladora",140,35]], team:["Dra. Marina Lopes","Sofia Martins","Carla Neves"], sample:[["09:00","Elaine Prado","Limpeza de pele","Marina"],["11:00","Bruna Melo","Drenagem linfática","Sofia"],["15:00","Fabiana Reis","Microagulhamento","Carla"]], insight:"Pacotes de cinco sessões elevaram a previsibilidade da receita em 31%." },
    petshop: { name:"Pet & Cia Care", segment:"Pet shop", icon:"●", color:"#71b9ef", pitch:"Cuidados recorrentes, histórico do pet e comunicação com os tutores.", clients:372, appointments:112, revenue:17680, occupancy:79, services:[["Banho",65,91],["Banho e tosa",110,68],["Tosa higiênica",55,46],["Hidratação",45,29]], team:["Paulo Vieira","Jéssica Moraes","Tiago Cunha"], sample:[["08:30","Thor · tutor Marcos","Banho e tosa","Paulo"],["10:00","Luna · tutora Bia","Banho","Jéssica"],["13:30","Mel · tutora Rita","Hidratação","Tiago"]], insight:"Os lembretes a cada 21 dias aumentaram o retorno recorrente dos pets em 27%." },
    bronzeamento: { name:"Sol Dourado Studio", segment:"Bronzeamento", icon:"☀", color:"#f1aa4c", pitch:"Sessões, pacotes e recomendações organizados para cada cliente.", clients:198, appointments:74, revenue:13650, occupancy:71, services:[["Bronze natural",130,52],["Bronze a jato",110,41],["Pacote 3 sessões",330,26],["Esfoliação corporal",85,19]], team:["Patrícia Melo","Daiane Silva"], sample:[["09:00","Carolina Reis","Bronze natural","Patrícia"],["11:00","Júlia Moura","Bronze a jato","Daiane"],["14:30","Amanda Luz","Esfoliação corporal","Patrícia"]], insight:"A oferta de pacotes no primeiro atendimento aumentou o ticket médio em 22%." },
    personal: { name:"Evolve Personal", segment:"Personal training", icon:"◆", color:"#67d49b", pitch:"Alunos, avaliações e sessões acompanhados com foco em resultado.", clients:86, appointments:124, revenue:19400, occupancy:84, services:[["Treino individual",100,72],["Treino em dupla",140,45],["Avaliação física",150,23],["Consultoria online",220,18]], team:["Marcelo Torres","Isabela Freire","Diego Matos"], sample:[["06:30","Ricardo Nunes","Treino individual","Marcelo"],["08:00","Lara e Paula","Treino em dupla","Isabela"],["17:30","Gustavo Lima","Avaliação física","Diego"]], insight:"Alunos com avaliação mensal mantêm frequência 19% maior que a média." },
    musica: { name:"Harmonia Escola", segment:"Aulas de música", icon:"♫", color:"#829ef5", pitch:"Turmas, horários e evolução dos alunos em perfeita harmonia.", clients:142, appointments:156, revenue:16380, occupancy:81, services:[["Aula de violão",90,64],["Aula de piano",110,48],["Aula de canto",100,52],["Teoria musical",75,31]], team:["Eduardo Campos","Mônica Reis","Felipe Braga"], sample:[["09:00","Gabriel Souza","Aula de violão","Eduardo"],["14:00","Beatriz Lima","Aula de piano","Mônica"],["16:30","Rafaela Nunes","Aula de canto","Felipe"]], insight:"Reposições organizadas pela agenda reduziram faltas não recuperadas em 34%." },
    clinica: { name:"Clínica Vitta", segment:"Clínica de saúde", icon:"✚", color:"#59c8df", pitch:"Agenda multiprofissional e jornada do paciente com mais clareza.", clients:512, appointments:186, revenue:42700, occupancy:78, services:[["Consulta inicial",250,61],["Retorno",160,73],["Fisioterapia",120,88],["Nutrição",200,42]], team:["Dra. Laura Nunes","Dr. André Reis","Fisio. Paula Lima"], sample:[["08:00","Marcos Vieira","Consulta inicial","Laura"],["09:30","Teresa Alves","Fisioterapia","Paula"],["11:00","João Nunes","Retorno","André"]], insight:"A confirmação antecipada diminuiu as ausências em 16% neste mês." },
    mentoria: { name:"Impulso Mentoria", segment:"Coaching e mentoria", icon:"▲", color:"#c28cf0", pitch:"Sessões, programas e evolução dos mentorados em uma visão estratégica.", clients:74, appointments:68, revenue:24600, occupancy:69, services:[["Sessão estratégica",350,34],["Mentoria individual",600,22],["Programa de carreira",1200,12],["Workshop em grupo",180,28]], team:["Helena Duarte","Rodrigo Paes"], sample:[["09:00","Daniel Martins","Sessão estratégica","Helena"],["11:00","Patrícia Moraes","Mentoria individual","Rodrigo"],["15:00","Grupo Liderança","Workshop em grupo","Helena"]], insight:"Programas com checkpoints quinzenais têm 92% de conclusão entre os mentorados." }
};

const money = new Intl.NumberFormat("pt-BR", { style:"currency", currency:"BRL", maximumFractionDigits:0 });
const $ = (id) => document.getElementById(id);
const keys = Object.keys(DEMOS);
let currentKey = new URLSearchParams(location.search).get("segmento");
if (!DEMOS[currentKey]) currentKey = "barbearia";

function initials(name) { return name.split(" ").slice(0,2).map(part => part[0]).join(""); }
function renderNavigation() {
    $("segmentNav").innerHTML = keys.map(key => `<button type="button" data-key="${key}" class="${key === currentKey ? "active" : ""}"><i>${DEMOS[key].icon}</i><span>${DEMOS[key].segment}</span></button>`).join("");
}
function renderDemo(key, updateUrl = true) {
    currentKey = key; const demo = DEMOS[key];
    document.documentElement.style.setProperty("--accent", demo.color);
    $("businessIcon").textContent = demo.icon; $("businessSegment").textContent = demo.segment.toUpperCase();
    $("businessName").textContent = demo.name; $("businessPitch").textContent = demo.pitch;
    const metricData = [["Clientes ativos", demo.clients, "+12 este mês"],["Agendamentos", demo.appointments, "nos últimos 30 dias"],["Faturamento", money.format(demo.revenue), "+14% vs. mês anterior"],["Ocupação da agenda", `${demo.occupancy}%`, "capacidade utilizada"]];
    $("metrics").innerHTML = metricData.map(([label,value,note]) => `<article><span>${label}</span><strong>${value}</strong><small>${note}</small></article>`).join("");
    $("appointments").innerHTML = demo.sample.map(([time,client,service,professional],index) => `<article class="appointment"><time>${time}</time><div><strong>${client}</strong><span>${service} · ${professional}</span></div><b class="${index === 0 ? "waiting" : "confirmed"}">${index === 0 ? "Aguardando" : "Confirmado"}</b></article>`).join("");
    $("services").innerHTML = demo.services.map(([name,price,count]) => `<article><i>${demo.icon}</i><div><strong>${name}</strong><span>${count} atendimentos</span></div><b>${money.format(price)}</b></article>`).join("");
    $("teamCount").textContent = `${demo.team.length} profissionais`;
    $("team").innerHTML = demo.team.map((name,index) => `<article><i>${initials(name)}</i><div><strong>${name}</strong><span>${Math.max(12, 31-index*6)} atendimentos na semana</span></div><b>Disponível</b></article>`).join("");
    const chartValues = [52,68,61,82,74,93,66];
    $("chart").innerHTML = chartValues.map((value,index) => `<div><span style="height:${value}%"></span><small>${["SEG","TER","QUA","QUI","SEX","SÁB","DOM"][index]}</small></div>`).join("");
    $("businessInsight").textContent = demo.insight;
    $("todayLabel").textContent = new Intl.DateTimeFormat("pt-BR", {day:"2-digit",month:"short"}).format(new Date());
    renderNavigation();
    if (updateUrl) history.replaceState(null, "", `?segmento=${key}`);
}

$("segmentNav").addEventListener("click", event => { const button = event.target.closest("[data-key]"); if (button) renderDemo(button.dataset.key); });
$("copyDemoLink").addEventListener("click", async () => {
    try { await navigator.clipboard.writeText(location.href); $("toast").textContent = "Link desta demonstração copiado!"; }
    catch { $("toast").textContent = "Copie o endereço exibido no navegador."; }
    $("toast").classList.add("show"); setTimeout(() => $("toast").classList.remove("show"), 2400);
});
renderDemo(currentKey, false);
