const params=new URLSearchParams(location.search);const slug=(params.get("empresa")||"").trim();
const state={page:null,service:null,professional:null,date:"",time:""};
const $=(id)=>document.getElementById(id);const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
function escapeHtml(value){const div=document.createElement("div");div.textContent=String(value??"");return div.innerHTML}
function environmentHref(path){const url=new URL(path,location.href);if(window.OGRITECH_ENV!=="production")url.searchParams.set("env",window.OGRITECH_ENV);return url}
function setError(message){$("loadingState").classList.add("hidden");$("bookingForm").classList.add("hidden");$("errorState").classList.remove("hidden");$("errorMessage").textContent=message}
function formatDate(value){return new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long"})}
function statusLabel(status){return({requested:"Aguardando confirmação",confirmed:"Confirmado",completed:"Concluído",cancelled:"Cancelado",no_show:"Não compareceu"})[status]||status}
function enable(id,enabled=true){$(id).classList.toggle("disabled-step",!enabled)}
function renderSummary(){if(!state.service||!state.professional||!state.date||!state.time)return;$("bookingSummary").innerHTML=`<strong>${escapeHtml(state.service.name)}</strong> com ${escapeHtml(state.professional.name)}<br>${escapeHtml(formatDate(state.date))}, às ${escapeHtml(state.time)} · ${money.format(Number(state.service.price))}`}
function renderProfessionals(){const available=state.page.professionals.filter((professional)=>(professional.service_ids||[]).includes(state.service.id));$("professionalChoices").innerHTML=available.map((professional)=>`<label class="choice-card"><input type="radio" name="professional" value="${professional.id}"><strong>${escapeHtml(professional.name)}</strong><small>${escapeHtml(professional.specialty||"Atendimento geral")}</small></label>`).join("")||'<p class="hint">Nenhum profissional disponível para este serviço.</p>';enable("professionalStep",available.length>0)}
async function loadSlots(){state.time="";enable("contactStep",false);$("slotChoices").innerHTML='<p class="hint">Buscando horários disponíveis…</p>';const{data,error}=await supabaseClient.rpc("public_available_slots",{target_slug:slug,target_service_id:state.service.id,target_employee_id:state.professional.id,target_date:state.date});if(error){$("slotChoices").innerHTML='<p class="hint">Não foi possível consultar os horários.</p>';return}const slots=(data||[]).map((row)=>String(row.slot_time).slice(0,5));$("slotChoices").innerHTML=slots.length?slots.map((time)=>`<button type="button" class="slot-button" data-time="${time}">${time}</button>`).join(""):'<p class="hint">Não há horários livres nesta data. Escolha outro dia.</p>'}
function showSuccess(booking){$("bookingForm").classList.add("hidden");$("successState").classList.remove("hidden");$("successReference").textContent=booking.reference;$("successDetail").innerHTML=`<strong>${escapeHtml(booking.service)}</strong><br>${escapeHtml(formatDate(booking.date))}, às ${escapeHtml(String(booking.time).slice(0,5))}<br>Profissional: ${escapeHtml(booking.professional)}<br>Status: ${escapeHtml(statusLabel(booking.status))}`;const hash=new URLSearchParams({reserva:booking.reference,token:booking.token});history.replaceState(null,"",`${location.pathname}${location.search}#${hash}`);try{localStorage.setItem(`ogritechPublicBooking:${booking.reference}`,booking.token)}catch{}}
async function loadManagement(reference,token){$("loadingState").classList.add("hidden");$("bookingForm").classList.add("hidden");$("manageState").classList.remove("hidden");const{data,error}=await supabaseClient.rpc("public_get_appointment",{target_reference:reference,target_token:token});if(error||!data){$("manageTitle").textContent="Reserva não encontrada";$("manageMessage").textContent="O link está incompleto, expirou ou não corresponde a uma reserva.";return}$("manageTitle").textContent=data.business;$("manageDetail").innerHTML=`Referência: <strong>${escapeHtml(data.reference)}</strong><br><strong>${escapeHtml(data.service)}</strong><br>${escapeHtml(formatDate(data.date))}, às ${escapeHtml(String(data.time).slice(0,5))}<br>Profissional: ${escapeHtml(data.professional)}<br>Status: <strong>${escapeHtml(statusLabel(data.status))}</strong>`;$("cancelBookingButton").classList.toggle("hidden",!data.can_cancel);$("cancelBookingButton").onclick=async()=>{if(!confirm("Deseja realmente cancelar este agendamento?"))return;const button=$("cancelBookingButton");button.disabled=true;const{data:cancelled,error:cancelError}=await supabaseClient.rpc("public_cancel_appointment",{target_reference:reference,target_token:token});if(cancelError||!cancelled){$("manageMessage").textContent="Não foi possível cancelar. Atualize a página e tente novamente.";button.disabled=false;return}button.classList.add("hidden");$("manageMessage").textContent="Agendamento cancelado com sucesso.";$("manageMessage").style.color="var(--ok)";$("manageDetail").innerHTML=$("manageDetail").innerHTML.replace(/Status: <strong>.*<\/strong>/,"Status: <strong>Cancelado</strong>")}}
async function initialize(){const hash=new URLSearchParams(location.hash.slice(1));const reference=hash.get("reserva"),token=hash.get("token");$("backToBooking").href=environmentHref(`./?empresa=${encodeURIComponent(slug)}`).href;if(reference&&token)return loadManagement(reference,token);if(!slug)return setError("O endereço da empresa não foi informado.");const{data,error}=await supabaseClient.rpc("public_booking_page",{target_slug:slug});if(error||!data)return setError("Confira o link recebido ou tente novamente mais tarde.");state.page=data;document.title=`Agendar com ${data.business.name} | Ogritech`;$("businessName").textContent=data.business.name;$("businessIntro").textContent=`${data.business.segment} · Escolha serviço, profissional e horário.`;$("serviceChoices").innerHTML=data.services.map((service)=>`<label class="choice-card"><input type="radio" name="service" value="${service.id}"><strong>${escapeHtml(service.name)}</strong><small>${escapeHtml(service.description||`${service.duration_minutes} minutos`)}</small><b>${money.format(Number(service.price))}</b></label>`).join("");const today=new Date(),max=new Date();max.setDate(max.getDate()+60);$("bookingDate").min=today.toISOString().slice(0,10);$("bookingDate").max=max.toISOString().slice(0,10);$("loadingState").classList.add("hidden");$("bookingForm").classList.remove("hidden")}
$("serviceChoices").addEventListener("change",(event)=>{state.service=state.page.services.find((item)=>item.id===event.target.value);state.professional=null;state.date="";state.time="";$("bookingDate").value="";renderProfessionals();enable("dateStep",false);enable("contactStep",false)});
$("professionalChoices").addEventListener("change",(event)=>{state.professional=state.page.professionals.find((item)=>item.id===event.target.value);state.date="";state.time="";$("bookingDate").value="";enable("dateStep");enable("contactStep",false)});
$("bookingDate").addEventListener("change",()=>{state.date=$("bookingDate").value;if(state.date)loadSlots()});
$("slotChoices").addEventListener("click",(event)=>{const button=event.target.closest("[data-time]");if(!button)return;$("slotChoices").querySelectorAll(".slot-button").forEach((item)=>item.classList.remove("active"));button.classList.add("active");state.time=button.dataset.time;enable("contactStep");renderSummary();$("contactStep").scrollIntoView({behavior:"smooth",block:"start"})});
$("bookingForm").addEventListener("submit",async(event)=>{event.preventDefault();const message=$("formMessage"),button=$("submitBooking");if(!state.time){message.textContent="Escolha um horário disponível.";return}button.disabled=true;button.textContent="Enviando solicitação…";message.textContent="";const{data,error}=await supabaseClient.rpc("public_create_appointment",{target_slug:slug,target_service_id:state.service.id,target_employee_id:state.professional.id,target_date:state.date,target_time:state.time,supplied_name:$("clientName").value.trim(),supplied_email:$("clientEmail").value.trim(),supplied_phone:$("clientPhone").value.trim(),accepted_privacy:$("privacyConsent").checked,website:$("clientWebsite").value});button.disabled=false;button.textContent="Solicitar agendamento";if(error){message.textContent=error.code==="23505"?"Este horário acabou de ser ocupado. Escolha outro horário.":(error.message||"Não foi possível concluir o agendamento.");if(error.code==="23505")loadSlots();return}showSuccess(data)});
$("newBookingButton").addEventListener("click",()=>{location.href=environmentHref(`./?empresa=${encodeURIComponent(slug)}`).href});
initialize().catch(()=>setError("Não foi possível carregar esta agenda agora."));
